# Archivo de configuración para la seguridad y las reglas de los usurios

security:
    encoders:
        # Módulo de encriptación
        AppBundle\Entity\User: bcrypt

    providers:
        # La base de datos y la entidad o Modelo que será usado para el login
        database_users:
            entity: { class: AppBundle:User, property: username }

    firewalls:
        secured_area:
            pattern: ^/

            # Usuarios anónimos necesario para que se pueda logear
            anonymous: true

            form_login:
                # router o dirección del login
                check_path: security_login
                login_path: security_login
                csrf_token_generator: security.csrf.token_manager

            logout:
                # Router o dirección del logout
                path: security_logout
                target: homepage

    access_control:
        # Aquí estan las distintas reglas para todos los usuario
        # que pueden hacer y que no, según sea la regla de negocio
        - { path: '^/admin/usuario/actualizar', roles: [ROLE_ADMIN, ROLE_GERENTE, ROLE_RECEPCIONISTA] }
        - { path: '^/admin/usuario', roles: ROLE_ADMIN }
        - { path: '^/admin/moto/crear', roles: [ROLE_ADMIN, ROLE_RECEPCIONISTA] }
        - { path: '^/admin/moto/actualizar', roles: [ROLE_ADMIN, ROLE_RECEPCIONISTA] }
        - { path: '^/admin/moto/eliminar', roles: ROLE_ADMIN }
        - { path: '^/admin/moto', roles: [ROLE_ADMIN, ROLE_RECEPCIONISTA] }
        - { path: '^/admin/reparacion/crear', roles: [ROLE_ADMIN, ROLE_RECEPCIONISTA] }
        - { path: '^/admin/reparacion/actualizar', roles: [ROLE_ADMIN, ROLE_RECEPCIONISTA] }
        - { path: '^/admin/reparacion/entregar', roles: ROLE_RECEPCIONISTA }
        - { path: '^/admin/reparacion/eliminar', roles: ROLE_ADMIN }
        - { path: '^/admin/reparacion', roles: [ROLE_ADMIN, ROLE_RECEPCIONISTA] }
        - { path: '^/admin/reporte', roles: [ROLE_ADMIN, ROLE_GERENTE] }
